import '../models/core_models.dart';
import '../models/market_models.dart';

class DummyData {
  static final List<ServiceModel> services = [
    ServiceModel(
      id: 's1',
      name: 'Makeup',
      description: 'Professional makeup for your special events.',
      iconAsset: 'assets/images/makeup.png',
      startingPrice: 3500,
      durationMinutes: 60,
      inclusions: ['Base makeup', 'Eye styling', 'Lashes', 'Lip color'],
    ),
    ServiceModel(
      id: 's2',
      name: 'Hair Styling',
      description: 'Elegant hairstyles tailored for you.',
      iconAsset: 'assets/images/hairstyling.png',
      startingPrice: 2000,
      durationMinutes: 45,
      inclusions: ['Wash & Dry', 'Styling', 'Finishing spray'],
    ),
    ServiceModel(
      id: 's3',
      name: 'Hair Cutting',
      description: 'Latest trends in hair cutting.',
      iconAsset: 'assets/images/haircut.png',
      startingPrice: 1500,
      durationMinutes: 30,
      inclusions: ['Consultation', 'Wash', 'Cut', 'Blow dry'],
    ),
    ServiceModel(
      id: 's4',
      name: 'Nail Art',
      description: 'Beautiful and intricate nail designs.',
      iconAsset: 'assets/images/nailart.png',
      startingPrice: 1200,
      durationMinutes: 45,
      inclusions: ['Color coat', 'Design', 'Top coat'],
    ),
    ServiceModel(
      id: 's5',
      name: 'Spa',
      description: 'Relaxing spa treatments.',
      iconAsset: 'assets/images/spa.png',
      startingPrice: 5000,
      durationMinutes: 90,
      inclusions: ['Full body massage', 'Aromatherapy', 'Hot stones'],
    ),
    ServiceModel(
      id: 's6',
      name: 'Waxing',
      description: 'Smooth and clean skin.',
      iconAsset: 'assets/images/waxing.png',
      startingPrice: 1000,
      durationMinutes: 30,
      inclusions: ['Pre-wax prep', 'Waxing', 'Soothing lotion'],
    ),
    ServiceModel(
      id: 's7',
      name: 'Manicure',
      description: 'Perfect care for your hands.',
      iconAsset: 'assets/images/manicure.png',
      startingPrice: 800,
      durationMinutes: 30,
      inclusions: ['Soak', 'Cuticle care', 'Massage', 'Polish'],
    ),
    ServiceModel(
      id: 's8',
      name: 'Pedicure',
      description: 'Revitalizing foot care.',
      iconAsset: 'assets/images/pedicure.png',
      startingPrice: 1000,
      durationMinutes: 40,
      inclusions: ['Soak', 'Exfoliation', 'Massage', 'Polish'],
    ),
    ServiceModel(
      id: 's9',
      name: 'Facial',
      description: 'Deep cleansing and glowing skin.',
      iconAsset: 'assets/images/facial.png',
      startingPrice: 2500,
      durationMinutes: 60,
      inclusions: ['Cleanse', 'Scrub', 'Mask', 'Massage'],
    ),
    ServiceModel(
      id: 's10',
      name: 'Threading',
      description: 'Precise hair removal for face.',
      iconAsset: 'assets/images/threading.png',
      startingPrice: 300,
      durationMinutes: 15,
      inclusions: ['Eyebrows', 'Upper lip', 'Chin'],
    ),
  ];

  static final List<StylistModel> stylists = [
    StylistModel(
      id: 'st1',
      name: 'Zara Khan',
      specialty: 'Makeup & Hair',
      experienceYears: 5,
      rating: 4.8,
      reviewCount: 124,
      profileImageUrl: 'assets/images/stylist1.png',
      serviceIds: ['s1', 's2', 's3'],
      portfolioImages: ['assets/images/port1.png', 'assets/images/port2.png'],
    ),
    StylistModel(
      id: 'st2',
      name: 'Aisha Ali',
      specialty: 'Spa & Facials',
      experienceYears: 8,
      rating: 4.9,
      reviewCount: 210,
      profileImageUrl: 'assets/images/stylist2.png',
      serviceIds: ['s5', 's9'],
      portfolioImages: ['assets/images/port3.png', 'assets/images/port4.png'],
    ),
    StylistModel(
      id: 'st3',
      name: 'Sana Malik',
      specialty: 'Nails & Waxing',
      experienceYears: 3,
      rating: 4.5,
      reviewCount: 89,
      profileImageUrl: 'assets/images/stylist3.png',
      serviceIds: ['s4', 's6', 's7', 's8', 's10'],
      portfolioImages: ['assets/images/port5.png', 'assets/images/port6.png'],
    ),
    StylistModel(
      id: 'st4',
      name: 'Fatima Ahmed',
      specialty: 'Bridal Expert',
      experienceYears: 10,
      rating: 5.0,
      reviewCount: 500,
      profileImageUrl: 'assets/images/stylist4.png',
      serviceIds: ['s1', 's2', 's9'],
      portfolioImages: ['assets/images/port7.png', 'assets/images/port8.png'],
    ),
  ];
}
